jobs:
  include:
    - stage: build
      branches:
      only:
      - master
      install: true
      script: ".travis/build.sh"
      cache:
        - ./cache
    - stage: osxdmg
        before_script:
          - pip install dmgbuild
        script: "./fiji-dmg-builder.sh"
