os: osx
language: python
install:
  - pip install dmgbuild
addons:
  ssh_known_hosts: downloads.imagej.net
before_script:
  - openssl aes-256-cbc -K $encrypted_9948786e33bf_key -iv $encrypted_9948786e33bf_iv -in .travis/ssh-rsa-key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
script: ".travis/build.sh"
cache:
  directories:
    - ./cache
