branches:
  only:
  - master
install:
  - mkdir -p ~/.ssh
  - echo 'downloads.imagej.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKHd/bb9AlriEl4OG5xiZf8GhkNCSiDBEeXyoV/i9G7vrigRpRcRAhJQjbgeNTHIAJNTTaT33of4oz74IxFoE1Y=' >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_9948786e33bf_key -iv $encrypted_9948786e33bf_iv
    -in .travis/ssh-rsa-key.enc -out ~/.ssh/id_rsa -d
  - chmod -R -w,o-rwx,g-rwx ~/.ssh
script: ".travis/build.sh"
cache: false
