name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '33 0,3,6,9,12,15,18,21 * * *' # once every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure the cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cache
        with:
          path: ~/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Execute the build
        run: ./build.sh
        env:
           WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
           WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
